# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :deployPro do
    clear_derived_data
    build_app(project: "OpenDocumentReader.xcodeproj", scheme: "ODR Full", xcargs: "-allowProvisioningUpdates")
    upload_to_app_store(
      app_identifier: "at.tomtasche.reader",
      skip_screenshots: true,
      skip_metadata: true
    )
    clear_derived_data
  end

  desc "Push a new release build to the App Store"
  lane :deployLite do
    clear_derived_data
    build_app(project: "OpenDocumentReader.xcodeproj", scheme: "ODR Lite", xcargs: "-allowProvisioningUpdates")
    upload_to_app_store(
      app_identifier: "at.tomtasche.reader.lite1",
      skip_screenshots: true,
      skip_metadata: true
    )
    clear_derived_data
  end

  lane :tests do
    # no clear_derived_data here: CI runners start clean anyway and locally it
    # only throws away the incremental build of a C++ heavy project
    run_tests(
      project: "OpenDocumentReader.xcodeproj",
      scheme: "ODR Full",
      prelaunch_simulator: true,
      xcargs: "-allowProvisioningUpdates"
    )
  end
end
