import UIKit

/// Stages screenshots with -ODRScreenshot <screen> in Debug builds.
/// Samples are generated by scripts/make-screenshot-documents.py and excluded from Release.
enum ScreenshotMode {

    /// One launch per screen; keep these cases aligned with scripts/store_screenshots.py.
    enum Screen: String {
        /// the document browser, with one of each format sitting in it
        case browser
        /// an ODF text document, read
        case text
        /// an ODF spreadsheet, with its sheet tabs
        case sheet
        /// the same reader on a Word file
        case office
        /// a pdf with a search under way
        case pdf
        /// a document being edited, keyboard up
        case edit
        /// the same edit as Lite shows it: the Pro tools dimmed, behind a badge
        case editLite = "edit-lite"

        /// Whether the screen is an edit, in either app.
        var isEdit: Bool { self == .edit || self == .editLite }

        /// The sample this screen opens, `nil` where it opens none.
        var sample: String? {
            switch self {
            case .browser: return nil
            case .text, .edit, .editLite: return "text"
            case .sheet: return "sheet"
            case .office: return "word"
            case .pdf: return "paper"
            }
        }
    }

    /// One entry in the folder, in the order the browser lists them. `source` is
    /// the sample holding its bytes, which only a filler sets.
    struct Sample {
        let name: String
        let format: String
        let source: String

        init(name: String, format: String, from source: String? = nil) {
            self.name = name
            self.format = format
            self.source = source ?? name
        }
    }

    static let folder = [
        Sample(name: "text", format: "odt"),
        Sample(name: "sheet", format: "ods"),
        Sample(name: "slides", format: "odp"),
        Sample(name: "word", format: "docx"),
        Sample(name: "cells", format: "xlsx"),
        Sample(name: "deck", format: "pptx"),
        Sample(name: "paper", format: "pdf"),
        Sample(name: "rows", format: "csv"),
        Sample(name: "notes", format: "txt"),

        // Fillers, so the folder looks like one somebody keeps things in. Each
        // is a copy of a document above under a name of its own, never opened.
        Sample(name: "meeting", format: "odt", from: "text"),
        Sample(name: "letter", format: "odt", from: "text"),
        Sample(name: "travel", format: "odt", from: "text"),
        Sample(name: "reading", format: "odt", from: "text"),
        Sample(name: "household", format: "ods", from: "sheet"),
        Sample(name: "hours", format: "ods", from: "sheet"),
        Sample(name: "stocktake", format: "ods", from: "sheet"),
        Sample(name: "kickoff", format: "odp", from: "slides"),
        Sample(name: "course", format: "odp", from: "slides"),
        Sample(name: "lease", format: "docx", from: "word"),
        Sample(name: "resume", format: "docx", from: "word"),
        Sample(name: "application", format: "docx", from: "word"),
        Sample(name: "expenses", format: "xlsx", from: "cells"),
        Sample(name: "inventory", format: "xlsx", from: "cells"),
        Sample(name: "review", format: "pptx", from: "deck"),
        Sample(name: "ticket", format: "pdf", from: "paper"),
        Sample(name: "warranty", format: "pdf", from: "paper"),
        Sample(name: "manual", format: "pdf", from: "paper"),
    ]

    /// Signals that the screenshot content is ready.
    static let readyIdentifier = "odr-screenshot-ready"

    /// Reads the Debug-only -ODRScreenshot launch argument through UserDefaults.
    static var screen: Screen? {
        #if DEBUG
            guard let name = UserDefaults.standard.string(forKey: "ODRScreenshot") else { return nil }

            return Screen(rawValue: name)
        #else
            return nil
        #endif
    }

    /// Where each sample ended up, by name, once it was laid out.
    private(set) static var laidOut: [String: URL] = [:]

    /// Reveal samples in reverse order because Recents lists the newest first.
    static var browserDocuments: [URL] {
        folder.reversed().compactMap { laidOut[$0.name] }
    }

    /// Prepare all sample files before the document browser loads.
    static func prepare() {
        guard screen != nil else { return }

        empty()

        let details = details()
        query = details?.search ?? ""

        let titles = details?.files ?? [:]
        laidOut = folder.reduce(into: [:]) { found, sample in
            found[sample.name] = layOut(sample, called: titles[sample.name] ?? sample.name)
        }
    }

    /// Remove samples from previous screenshot runs and locales.
    private static func empty() {
        guard let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first,
            let existing = try? FileManager.default.contentsOfDirectory(
                at: documents, includingPropertiesForKeys: nil)
        else {
            return
        }

        for file in existing {
            try? FileManager.default.removeItem(at: file)
        }
    }

    /// Localized sample names and search text from make-screenshot-documents.py.
    private struct Details: Decodable {
        let files: [String: String]
        let search: String
    }

    private static func details() -> Details? {
        guard
            let url = Bundle.main.url(forResource: "screenshot-names", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let all = try? JSONDecoder().decode([String: Details].self, from: data)
        else {
            assertionFailure("no screenshot-names.json bundled - run scripts/make-screenshot-documents.py")

            return nil
        }

        for language in Bundle.main.preferredLocalizations where all[language] != nil {
            return all[language]
        }

        return all["en"]
    }

    /// The word searched for in the localized text sample.
    private(set) static var query = ""

    /// Copy the localized sample to Documents, falling back to English.
    private static func layOut(_ sample: Sample, called title: String) -> URL? {
        var source: URL?
        for language in Bundle.main.preferredLocalizations + ["en"] {
            source = Bundle.main.url(
                forResource: "sample-\(sample.source)-\(language)", withExtension: sample.format)

            if source != nil { break }
        }

        guard let source else {
            assertionFailure("no \(sample.source) sample bundled - run scripts/make-screenshot-documents.py")

            return nil
        }

        guard let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return nil
        }

        let destination = documents.appendingPathComponent("\(title).\(sample.format)")

        do {
            try? FileManager.default.removeItem(at: destination)
            try FileManager.default.copyItem(at: source, to: destination)
        } catch {
            assertionFailure("could not lay out \(destination.lastPathComponent): \(error)")

            return nil
        }

        return destination
    }

    /// The document this screen opens, once ``prepare()`` has laid it out.
    static func document(for screen: Screen) -> URL? {
        guard let sample = screen.sample else { return nil }

        return laidOut[sample]
    }

    /// Marks the view the test waits for. Does nothing outside a screenshot run.
    static func markReady(_ view: UIView) {
        guard screen != nil else { return }

        view.accessibilityIdentifier = readyIdentifier
    }
}
