name: OpenDocumentReader-iOS
on: [push]

jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOMTASCHE }}
          submodules: true

      - uses: futureware-tech/simulator-action@v1
        with:
          os_version: ">=14.5"

      - name: pods
        run: pod install

      - name: brew
        run: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
      - name: fix ninja install
        run: rm '/usr/local/bin/2to3'
      - name: ninja
        run: brew install ninja

      # https://stackoverflow.com/a/57758679/198996
      - name: bundler
        run: gem install bundler:1.17.3
      - name: fastlane
        run: bundle install

      - name: pip
        run: python3 -m ensurepip
      - name: conan
        run: pip3 install conan
      - name: conan repo
        run: conan remote add odr https://odr.jfrog.io/artifactory/api/conan/odr-conan

      - name: run tests
        run: bundle exec fastlane tests
#      - uses: actions/upload-artifact@v2
#        if: ${{ always() }}
#        with:
#          name: logs
#          path: |
#            /Users/runner/Library/Developer/Xcode/DerivedData/OpenDocumentReader-*/
