name: OpenDocumentReader-iOS
on: [push]

jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOMTASCHE }}
          submodules: true

      - name: pods
        run: pod install

      # https://stackoverflow.com/a/57758679/198996
      - name: bundler
        run: gem install bundler:1.17.3
      - name: fastlane
        run: bundle install

      - name: pip
        run: python3 -m ensurepip
      - name: conan
        run: pip install conan

      - name: run tests
        run: bundle exec fastlane tests
#      - uses: actions/upload-artifact@v2
#        if: ${{ always() }}
#        with:
#          name: logs
#          path: |
#            /Users/runner/Library/Developer/Xcode/DerivedData/OpenDocumentReader-*/
