name: OpenDocumentReader-iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        device:
          - "iPhone 14 Pro"
          - "iPhone 15 Pro"
          - "iPad Pro (12.9-inch) (6th generation)"
        ios:
          - "16.4"
          - "17.4"
      fail-fast: false
    env:
      GYM_SKIP_CODESIGNING: true
      GYM_SKIP_ARCHIVE: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.3"

      - name: install pods
        run: pod install

      # https://stackoverflow.com/a/57758679/198996
      - name: install bundler
        run: gem install bundler:1.17.3
      - name: install fastlane
        run: bundle install

      - name: install pip
        run: python3 -m ensurepip
      - name: install conan
        run: pip3 install conan

      - name: conan remote
        run: conan remote add --index 0 odr https://artifactory.opendocument.app/artifactory/api/conan/conan
      - name: conan login
        run: conan remote login odr admin --password ${{ secrets.ARTIFACTORY }}
  
      - name: conan profile
        run: conan profile detect

      - name: conan install
        run: >
          conan install conan/
          --output-folder=conan-output
          --build=missing
          --profile:host=conan/profiles/ios-simulator
          -s build_type=Release
          -s "&:build_type=RelWithDebInfo"
          -s "odrcore/*:build_type=RelWithDebInfo"

      - name: run tests
        run: 'bundle exec fastlane build device:"${{ matrix.device }}" ios:"${{ matrix.ios }}"'

      - name: upload binaries to conan repo
        run: conan upload "*" --check --confirm --remote odr

  test:
    runs-on: macos-14
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.3"

      - name: install pods
        run: pod install

      # https://stackoverflow.com/a/57758679/198996
      - name: install bundler
        run: gem install bundler:1.17.3
      - name: install fastlane
        run: bundle install

      - name: install pip
        run: python3 -m ensurepip
      - name: install conan
        run: pip3 install conan

      - name: conan remote
        run: conan remote add --index 0 odr https://artifactory.opendocument.app/artifactory/api/conan/conan
      - name: conan login
        run: conan remote login odr admin --password ${{ secrets.ARTIFACTORY }}
  
      - name: conan profile
        run: conan profile detect

      - name: conan install
        run: >
          conan install conan/
          --output-folder=conan-output
          --build=missing
          --profile:host=conan/profiles/ios-simulator
          -s build_type=Release
          -s "&:build_type=RelWithDebInfo"
          -s "odrcore/*:build_type=RelWithDebInfo"

      - name: run tests
        run: bundle exec fastlane tests

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: |
            /Users/runner/Library/Developer/Xcode/DerivedData/OpenDocumentReader-*/

      - name: upload binaries to conan repo
        run: conan upload "*" --check --confirm --remote odr
