name: OpenDocumentReader-iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.4"

      - name: install pods
        run: pod install

      # https://stackoverflow.com/a/57758679/198996
      - name: install bundler
        run: gem install bundler:1.17.3
      - name: install fastlane
        run: bundle install

      - name: install conan
        run: pip3 install conan

      - name: conan remote
        run: conan remote add --index 0 odr https://artifactory.opendocument.app/artifactory/api/conan/conan
      - name: conan login
        run: conan remote login odr admin --password ${{ secrets.ARTIFACTORY }}

      - name: conan profile
        run: conan profile detect

      - name: conan install
        run: >
          conan install conan/
          --output-folder=conan-output
          --build=missing
          --profile:host=conan/profiles/ios-simulator-arm64
          -s build_type=Release
          -s "&:build_type=RelWithDebInfo"
          -s "odrcore/*:build_type=RelWithDebInfo"

      - name: run tests
        run: bundle exec fastlane tests

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: |
            /Users/runner/Library/Developer/Xcode/DerivedData/OpenDocumentReader-*/

      - name: upload binaries to conan repo
        run: conan upload "*" --check --confirm --remote odr
